[package]
name = "malcentasko-contracts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.10.11"
arrayref = "0.3.6"
thiserror = "1.0.31"

[features]
no-entrypoint = []
